close all; clear;

%% all shear diagrams
generate_shear_diagram( ...
    [
        0, 93.55;
        0.03, -93.55;
        0.06, 0
    ], ...
    'Input Shaft Y' ,'x (m)', 'V_y (N)' ...
);

generate_shear_diagram( ...
    [
        0, 361.7;
        0.03, -361.7;
        0.06, 0
    ], ...
    'Input Shaft Z' ,'x (m)', 'V_z (N)' ...
);

generate_shear_diagram( ...
    [
        0, 152;
        0.05, 60.79;
        0.10, -212.8;
        0.15, 0
    ], ...
    'Countershaft Y' ,'x (m)', 'V_y (N)' ...
);

generate_shear_diagram( ...
    [
        0,-117.6;
        0.05, -470.3;
        0.10, 587.7;
        0.15, 0
    ], ...
    'Countershaft Z' ,'x (m)', 'V_z (N)' ...
);

generate_shear_diagram( ...
    [
        0, 266.8;
        0.03, -266.8;
        0.06, 0
    ], ...
    'Output Y' ,'x (m)', 'V_y (N)' ...
);

generate_shear_diagram( ...
    [
        0, -1032;
        0.03, 1032;
        0.06, 0
    ], ...
    'Output Z' ,'x (m)', 'V_z (N)' ...
);


%% all bending diagrams
generate_moment_diagram( ...
    [
        0, 0;
        0.03, 2.81;
        0.06, 0
    ], ...
    'Input Shaft Y' ,'x (m)', 'M_y (N-m)' ...
);

generate_moment_diagram( ...
    [
        0, 0;
        0.03, 10.851;
        0.06, 0
    ], ...
    'Input Shaft Z' ,'x (m)', 'M_z (N-m)' ...
);

generate_moment_diagram( ...
    [
        0, 0;
        0.05, 7.6;
        0.10, 10.64;
        0.15, 0
    ], ...
    'Countershaft Y' ,'x (m)', 'M_y (N-m)' ...
);

generate_moment_diagram( ...
    [
        0, 0;
        0.05, -5.88;
        0.10, -29.395;
        0.15, 0
    ], ...
    'Countershaft Z' ,'x (m)', 'M_z (N-m)' ...
);

generate_moment_diagram( ...
    [
        0, 0;
        0.03, 8;
        0.06, 0
    ], ...
    'Output Shaft Y' ,'x (m)', 'M_y (N-m)' ...
);

generate_moment_diagram( ...
    [
        0, 0;
        0.03, -30.96;
        0.06, 0
    ], ...
    'Output Shaft Z' ,'x (m)', 'M_z (N-m)' ...
);

%% all torque diagrams
generate_shear_diagram( ...
    [
        0, 7.958;
        0.06, 0
    ], ...
    'Input Torque' ,'x (m)', 'T (N-m)' ...
);

generate_shear_diagram( ...
    [
        0, 0;
        0.05, -23.38;
        0.1, 0;
        0.15, 0
    ], ...
    'Countershaft Torque' ,'x (m)', 'T (N)' ...
);

generate_shear_diagram( ...
    [
        0, 68.08;
        0.06, 0
    ], ...
    'Output Torque' ,'x (m)', 'T (N)' ...
);